- name: Go install {{ git_repo }}
  ansible.builtin.shell:
    cmd: ASDF_DIR={{ ansible_env.HOME }}/.asdf . {{ ansible_env.HOME }}/.asdf/asdf.sh && GOBIN={{ ansible_env.HOME }}/.local/bin go install {{ git_repo }}