- name: Install Latest Golang
  hosts: localhost
  connection: local
  tags:
    - golang
  tasks:
    - name: Include template for Golang installation
      ansible.builtin.include_tasks: asdf-packages.yaml
      vars:
        software_name: golang
        plugin_name: golang
        software_version: latest
