- name: Install Latest Golang
  hosts: localhost
  connection: local
  tags:
    - nodejs
  tasks:
    - name: Install golang plugin
      ansible.builtin.shell:
        cmd: "ASDF_DIR={{ ansible_env.HOME }}/.asdf . {{ ansible_env.HOME }}/.asdf/asdf.sh && asdf plugin-add golang https://github.com/kennyp/asdf-golang.git"
    - name: Install golang
      ansible.builtin.shell:
        cmd: "ASDF_DIR={{ ansible_env.HOME }}/.asdf . {{ ansible_env.HOME }}/.asdf/asdf.sh && asdf install golang latest"
    - name: Set global version
      ansible.builtin.shell:
        cmd: "ASDF_DIR={{ ansible_env.HOME }}/.asdf . {{ ansible_env.HOME }}/.asdf/asdf.sh && asdf global golang latest"
