- hosts: localhost
  name: Install Neovim
  tags:
    - nvim
  tasks:
    - name: Include template for Neovim installation
      ansible.builtin.include_tasks: asdf-packages.yaml
      vars:
        software_name: neovim
        plugin_name: neovim
        software_version: latest
    - name: Install astronvim
      ansible.builtin.git:
        repo: "https://github.com/AstroNvim/AstroNvim"
        dest: ~/.config/nvim
        depth: 1
        clone: true
