- name: Install Latest Node.js
  hosts: localhost
  connection: local
  tags:
    - nodejs
  tasks:
    - name: Include template for Nodejs installation
      ansible.builtin.include_tasks: asdf-packages.yaml
      vars:
        software_name: nodejs
        plugin_name: nodejs
        software_version: latest
